# Generated by Django 5.1.7 on 2025-11-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user_alter_poll_owner_alter_voterecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super_user',
            field=models.BooleanField(default=False),
        ),
    ]
